openapi: 3.0.0
info:
  title: 'SocialMedia API'
  description: 'API for Fetching, Saving, Updating and Deleting a social media account'
  version: '0.1.9'
servers:
  - url: 'http://localhost:8080/api/v1'
    description: 'Development server'
paths:
  /social-media/accounts:
    get:
      tags:
        - 'SocialMedia'
      operationId: 'getSocialMediaAccounts'
      summary: 'Returns a list of social media accounts.'
      description: 'Fetch all media accounts from database.'
      responses:
        '200':    # status code
          description: 'A JSON array of social media accounts'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Account'

components:
  schemas:
    Account:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: 'account'