/**
 * Authentication API
 * API for Registering a new user and logging in an existing user.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: viktorzdravkovski995@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface RegistrationConfirmation { 
    message?: string;
    status?: number;
}
