/**
 * TaskTrackingTool API
 * API for showing information about the users.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: viktorzdravkovski995@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface CurrentUserResponse { 
    username?: string;
    fullName?: string;
    email?: string;
    roles?: Array<string>;
}
